AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

Globals:
  Function:
    Timeout: 30

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2_start_function
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt Role.Arn

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      RoleName: EC2StartFunctionRole
      Policies:
        - PolicyName: InlinePolicyEC2StartFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:StartInstances"
                  - "ec2:DescribeTags"
                  - "ec2:DescribeInstanceStatus"
                  - "ecs:DescribeServices"
                  - "ecs:UpdateService"
                  - "ecs:ListServices"
                  - "ecs:ListClusters"
                  - "ecs:DescribeClusters"
                Resource:
                  - "*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"